-- VHDL Entity ece411.BR_add1.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY BR_add1 IS
   PORT( 
      BR_add_EX      : OUT    lc3b_word;
      ADDRESSMUX2Out : IN     LC3b_word;
      ADDRESSMUX1Out : IN     LC3b_word;
      clk            : IN     std_logic
   );

END BR_add1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF BR_add1 IS 
BEGIN


END generatedInstance;
