-- VHDL Entity ece411.BRlog1.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY BRlog1 IS
   PORT( 
      BRANCHLOAD_MEM : OUT    std_logic;
      CheckN         : IN     std_logic;
      CheckP         : IN     std_logic;
      CheckZ         : IN     std_logic;
      n              : IN     std_logic;
      z              : IN     std_logic;
      p              : IN     std_logic;
      opcode_MEM     : IN     lc3b_opcode;
      clk            : IN     std_logic
   );

END BRlog1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF BRlog1 IS 
BEGIN


END generatedInstance;
