-- VHDL Entity ece411.ControlSplit_WB1.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ControlSplit_WB1 IS
   PORT( 
      ControlWord_WB : IN     LC3b_ControlWord;
      regwrite_wb    : OUT    std_logic;
      WBMUXSel       : OUT    std_logic_vector (1 DOWNTO 0);
      clk            : IN     std_logic
   );

END ControlSplit_WB1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ControlSplit_WB1 IS 
BEGIN


END generatedInstance;
