-- VHDL Entity ece411.ControlReg1.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY ControlReg1 IS
   PORT( 
      ControlWord_ID : OUT    LC3B_ControlWord;
      RESET_L        : IN     std_logic;
      IR_Bit11       : IN     std_logic;
      IR_Bit5        : IN     std_logic;
      opcode_ID      : IN     LC3B_Opcode;
      clk            : IN     std_logic
   );

END ControlReg1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF ControlReg1 IS 
BEGIN


END generatedInstance;
