-- VHDL Entity ece411.D_Mapped_Cache1k.symbol
--
-- Created:
--          by - tmurray5.stdt (eelnx25.ews.illinois.edu)
--          at - 21:50:50 10/28/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY D_Mapped_Cache1k IS
   PORT( 
      dataIN    : IN     lc3b_oword;
      dirtyIN   : IN     std_logic;
      index     : IN     lc3b_index6;
      reset_l   : IN     std_logic;
      tagIN     : IN     lc3b_l1tag;
      writeData : IN     std_logic;
      ValidOUT  : OUT    std_logic;
      dataOUT   : OUT    lc3b_oword;
      dirtyOUT  : OUT    std_logic;
      tagOUT    : OUT    lc3b_l1tag
   );

-- Declarations

END D_Mapped_Cache1k ;

--
-- VHDL Architecture ece411.D_Mapped_Cache1k.struct
--
-- Created:
--          by - tmurray5.stdt (eelnx25.ews.illinois.edu)
--          at - 21:50:50 10/28/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF D_Mapped_Cache1k IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT DataArray1K
   PORT (
      index     : IN     lc3b_index6 ;
      reset_l   : IN     std_logic ;
      writeData : IN     std_logic ;
      dataIN    : IN     lc3b_oword ;
      dataOUT   : OUT    lc3b_oword 
   );
   END COMPONENT;
   COMPONENT dirtyArray1k
   PORT (
      index     : IN     lc3b_index6 ;
      reset_l   : IN     std_logic ;
      writeData : IN     std_logic ;
      dirtyIN   : IN     std_logic ;
      dirtyOUT  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT tagArray1K
   PORT (
      index     : IN     lc3b_index6 ;
      reset_l   : IN     std_logic ;
      writeData : IN     std_logic ;
      tagIN     : IN     lc3b_l1tag ;
      tagOUT    : OUT    lc3b_l1tag 
   );
   END COMPONENT;
   COMPONENT validArray1k
   PORT (
      index     : IN     lc3b_index6 ;
      reset_l   : IN     std_logic ;
      writeData : IN     std_logic ;
      ValidOUT  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DataArray1K USE ENTITY ece411.DataArray1K;
   FOR ALL : dirtyArray1k USE ENTITY ece411.dirtyArray1k;
   FOR ALL : tagArray1K USE ENTITY ece411.tagArray1K;
   FOR ALL : validArray1k USE ENTITY ece411.validArray1k;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aDataArray1k : DataArray1K
      PORT MAP (
         index     => index,
         reset_l   => reset_l,
         writeData => writeData,
         dataIN    => dataIN,
         dataOUT   => dataOUT
      );
   aDirtyArray1k : dirtyArray1k
      PORT MAP (
         index     => index,
         reset_l   => reset_l,
         writeData => writeData,
         dirtyIN   => dirtyIN,
         dirtyOUT  => dirtyOUT
      );
   aTagArray1k : tagArray1K
      PORT MAP (
         index     => index,
         reset_l   => reset_l,
         writeData => writeData,
         tagIN     => tagIN,
         tagOUT    => tagOUT
      );
   aValidArray1k : validArray1k
      PORT MAP (
         index     => index,
         reset_l   => reset_l,
         writeData => writeData,
         ValidOUT  => ValidOUT
      );

END struct;
