-- VHDL Entity ece411.DATAFORMATTER.generatedInstance
--
-- Created:
--          by - jpatel71.stdt (eelnx34.ews.illinois.edu)
--          at - 12:13:27 10/21/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY DATAFORMATTER IS
   PORT( 
      EX_DATAOUT : IN     lc3b_word;
      DATAOUt    : OUT    LC3b_word
   );

END DATAFORMATTER ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF DATAFORMATTER IS 
BEGIN


END generatedInstance;
