-- VHDL Entity ece411.HazardDet.generatedInstance
--
-- Created:
--          by - bjohns38.stdt (eelnx29.ews.illinois.edu)
--          at - 17:53:34 11/07/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY HazardDet IS
   PORT( 
      IR8_6_ID    : IN     LC3B_REG;
      IR_2_0_ID   : IN     STD_LOGIC_VECTOR (2 DOWNTO 0);
      SRCA_EX     : IN     std_logic;
      SRCB_EX     : IN     std_logic;
      WBMUXSEL_EX : IN     std_logic_vector (1 DOWNTO 0);
      clk         : IN     std_logic
   );

END HazardDet ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF HazardDet IS 
BEGIN


END generatedInstance;
