-- VHDL Entity ece411.high_byte_select.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx3.ews.illinois.edu)
--          at - 13:41:40 10/07/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY high_byte_select IS
   PORT( 
      clk : IN     std_logic
   );

END high_byte_select ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF high_byte_select IS 
BEGIN


END generatedInstance;
