-- VHDL Entity ece411.LEFTSHIFTER.generatedInstance
--
-- Created:
--          by - jpatel71.stdt (eelnx34.ews.illinois.edu)
--          at - 12:13:27 10/21/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LEFTSHIFTER IS
   PORT( 
      ADRESSMUX2Out : IN     LC3b_word;
      LEFTSHIFTOUT  : OUT    LC3b_word;
      LEFTSHIFT     : IN     std_logic
   );

END LEFTSHIFTER ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF LEFTSHIFTER IS 
BEGIN


END generatedInstance;
