-- VHDL Entity ece411.LEFTSHIFT_ZEXT.generatedInstance
--
-- Created:
--          by - jpatel71.stdt (eelnx34.ews.illinois.edu)
--          at - 12:13:27 10/21/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LEFTSHIFT_ZEXT IS
   PORT( 
      imm8           : IN     LC3b_imm8;
      LEFTSHFZEXTOut : OUT    LC3b_word
   );

END LEFTSHIFT_ZEXT ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF LEFTSHIFT_ZEXT IS 
BEGIN


END generatedInstance;
