-- VHDL Entity ece411.LoadGenerator1.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LoadGenerator1 IS
   PORT( 
      D_MRESP_H   : IN     std_logic;
      I_MRESP_H   : IN     std_logic;
      D_MWRITEH_L : IN     std_logic;
      D_MWRITEL_L : IN     std_logic;
      D_MREAD_L   : IN     std_logic;
      load        : OUT    std_logic;
      clk         : IN     std_logic
   );

END LoadGenerator1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF LoadGenerator1 IS 
BEGIN


END generatedInstance;
