-- VHDL Entity ece411.LRU_L2.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (dcllnx27.ews.illinois.edu)
--          at - 21:56:17 11/09/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY LRU_L2 IS
   PORT( 
      LRUOut  : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0);
      reset_l : IN     std_logic;
      index   : IN     lc3b_index5
   );

END LRU_L2 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF LRU_L2 IS 
BEGIN


END generatedInstance;
