-- VHDL Entity ece411.mp2_cpu.symbol
--
-- Created:
--          by - tmurray5.stdt (eelnx37.ews.illinois.edu)
--          at - 15:42:50 10/14/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY mp2_cpu IS
   PORT( 
      RESET_L : IN     std_logic;
      START_H : IN     std_logic;
      clk     : IN     std_logic
   );

-- Declarations

END mp2_cpu ;

--
-- VHDL Architecture ece411.mp2_cpu.struct
--
-- Created:
--          by - tmurray5.stdt (eelnx37.ews.illinois.edu)
--          at - 15:42:50 10/14/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF mp2_cpu IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ADDRESS     : LC3b_word;
   SIGNAL ADDRESS0    : std_logic;
   SIGNAL ALUMuxSel   : LC3b_4MUX_Sel;
   SIGNAL ALUop       : LC3b_aluop;
   SIGNAL AdderMuxSel : std_logic;
   SIGNAL ByteSel     : std_logic;
   SIGNAL CheckN      : std_logic;
   SIGNAL CheckP      : std_logic;
   SIGNAL CheckZ      : std_logic;
   SIGNAL D           : std_logic;
   SIGNAL DATAIN      : LC3b_word;
   SIGNAL DATAOUT     : LC3b_word;
   SIGNAL DestMuxSel  : std_logic;
   SIGNAL LoadIR      : std_logic;
   SIGNAL LoadMAR     : std_logic;
   SIGNAL LoadMDR     : std_logic;
   SIGNAL LoadNZP     : std_logic;
   SIGNAL LoadPC      : std_logic;
   SIGNAL MARMuxSel   : lc3b_4mux_sel;
   SIGNAL MDRMuxSel   : std_logic;
   SIGNAL MREAD_L     : std_logic;
   SIGNAL MRESP_H     : std_logic;
   SIGNAL MWRITEH_L   : std_logic;
   SIGNAL MWRITEL_L   : std_logic;
   SIGNAL Opcode      : LC3B_Opcode;
   SIGNAL PCMuxSel    : LC3B_4MUX_SEL;
   SIGNAL RFMuxSel    : LC3B_4MUX_SEL;
   SIGNAL RegWrite    : std_logic;
   SIGNAL StoreSR     : std_logic;
   SIGNAL bit11       : std_logic;
   SIGNAL bit5        : std_logic;
   SIGNAL n           : std_logic;
   SIGNAL p           : std_logic;
   SIGNAL z           : std_logic;


   -- Component Declarations
   COMPONENT Control
   PORT (
      ADDRESS0    : IN     std_logic ;
      CheckN      : IN     std_logic ;
      CheckP      : IN     std_logic ;
      CheckZ      : IN     std_logic ;
      D           : IN     std_logic ;
      MRESP_H     : IN     std_logic ;
      Opcode      : IN     LC3B_Opcode ;
      RESET_L     : IN     std_logic ;
      START_H     : IN     std_logic ;
      bit11       : IN     std_logic ;
      bit5        : IN     std_logic ;
      clk         : IN     std_logic ;
      n           : IN     std_logic ;
      p           : IN     std_logic ;
      z           : IN     std_logic ;
      ALUMuxSel   : OUT    LC3b_4MUX_Sel ;
      ALUop       : OUT    LC3b_aluop ;
      AdderMuxSel : OUT    std_logic ;
      ByteSel     : OUT    std_logic ;
      DestMuxSel  : OUT    std_logic ;
      LoadIR      : OUT    std_logic ;
      LoadMAR     : OUT    std_logic ;
      LoadMDR     : OUT    std_logic ;
      LoadNZP     : OUT    std_logic ;
      LoadPC      : OUT    std_logic ;
      MARMuxSel   : OUT    lc3b_4mux_sel ;
      MDRMuxSel   : OUT    std_logic ;
      MREAD_L     : OUT    std_logic ;
      MWRITEH_L   : OUT    std_logic ;
      MWRITEL_L   : OUT    std_logic ;
      PCMuxSel    : OUT    LC3B_4MUX_SEL ;
      RFMuxSel    : OUT    LC3B_4MUX_SEL ;
      RegWrite    : OUT    std_logic ;
      StoreSR     : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Datapath
   PORT (
      ALUMuxSel   : IN     LC3b_4MUX_Sel ;
      ALUop       : IN     LC3b_aluop ;
      AdderMuxSel : IN     std_logic ;
      ByteSel     : IN     std_logic ;
      DATAIN      : IN     LC3b_word ;
      DestMuxSel  : IN     std_logic ;
      LoadIR      : IN     std_logic ;
      LoadMAR     : IN     std_logic ;
      LoadMDR     : IN     std_logic ;
      LoadNZP     : IN     std_logic ;
      LoadPC      : IN     std_logic ;
      MARMuxSel   : IN     lc3b_4mux_sel ;
      MDRMuxSel   : IN     std_logic ;
      PCMuxSel    : IN     LC3B_4MUX_SEL ;
      RESET_L     : IN     std_logic ;
      RFMuxSel    : IN     LC3B_4MUX_SEL ;
      RegWrite    : IN     std_logic ;
      StoreSR     : IN     std_logic ;
      clk         : IN     std_logic ;
      ADDRESS     : OUT    LC3b_word ;
      ADDRESS0    : OUT    std_logic ;
      CheckN      : OUT    std_logic ;
      CheckP      : OUT    std_logic ;
      CheckZ      : OUT    std_logic ;
      D           : OUT    std_logic ;
      DATAOUT     : OUT    LC3b_word ;
      Opcode      : OUT    LC3B_Opcode ;
      bit11       : OUT    std_logic ;
      bit5        : OUT    std_logic ;
      n           : OUT    std_logic ;
      p           : OUT    std_logic ;
      z           : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Memory
   PORT (
      ADDRESS   : IN     LC3b_word ;
      Clk       : IN     std_logic ;
      DATAOUT   : IN     LC3b_word ;
      MREAD_L   : IN     std_logic ;
      MWRITEH_L : IN     std_logic ;
      MWRITEL_L : IN     std_logic ;
      RESET_L   : IN     std_logic ;
      DATAIN    : OUT    lc3b_word ;
      MRESP_H   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Control USE ENTITY ece411.Control;
   FOR ALL : Datapath USE ENTITY ece411.Datapath;
   FOR ALL : Memory USE ENTITY ece411.Memory;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   ControlUnit : Control
      PORT MAP (
         ADDRESS0    => ADDRESS0,
         CheckN      => CheckN,
         CheckP      => CheckP,
         CheckZ      => CheckZ,
         D           => D,
         MRESP_H     => MRESP_H,
         Opcode      => Opcode,
         RESET_L     => RESET_L,
         START_H     => START_H,
         bit11       => bit11,
         bit5        => bit5,
         clk         => clk,
         n           => n,
         p           => p,
         z           => z,
         ALUMuxSel   => ALUMuxSel,
         ALUop       => ALUop,
         AdderMuxSel => AdderMuxSel,
         ByteSel     => ByteSel,
         DestMuxSel  => DestMuxSel,
         LoadIR      => LoadIR,
         LoadMAR     => LoadMAR,
         LoadMDR     => LoadMDR,
         LoadNZP     => LoadNZP,
         LoadPC      => LoadPC,
         MARMuxSel   => MARMuxSel,
         MDRMuxSel   => MDRMuxSel,
         MREAD_L     => MREAD_L,
         MWRITEH_L   => MWRITEH_L,
         MWRITEL_L   => MWRITEL_L,
         PCMuxSel    => PCMuxSel,
         RFMuxSel    => RFMuxSel,
         RegWrite    => RegWrite,
         StoreSR     => StoreSR
      );
   theDatapath : Datapath
      PORT MAP (
         ALUMuxSel   => ALUMuxSel,
         ALUop       => ALUop,
         AdderMuxSel => AdderMuxSel,
         ByteSel     => ByteSel,
         DATAIN      => DATAIN,
         DestMuxSel  => DestMuxSel,
         LoadIR      => LoadIR,
         LoadMAR     => LoadMAR,
         LoadMDR     => LoadMDR,
         LoadNZP     => LoadNZP,
         LoadPC      => LoadPC,
         MARMuxSel   => MARMuxSel,
         MDRMuxSel   => MDRMuxSel,
         PCMuxSel    => PCMuxSel,
         RESET_L     => RESET_L,
         RFMuxSel    => RFMuxSel,
         RegWrite    => RegWrite,
         StoreSR     => StoreSR,
         clk         => clk,
         ADDRESS     => ADDRESS,
         ADDRESS0    => ADDRESS0,
         CheckN      => CheckN,
         CheckP      => CheckP,
         CheckZ      => CheckZ,
         D           => D,
         DATAOUT     => DATAOUT,
         Opcode      => Opcode,
         bit11       => bit11,
         bit5        => bit5,
         n           => n,
         p           => p,
         z           => z
      );
   DRAM : Memory
      PORT MAP (
         ADDRESS   => ADDRESS,
         DATAOUT   => DATAOUT,
         MREAD_L   => MREAD_L,
         MWRITEH_L => MWRITEH_L,
         MWRITEL_L => MWRITEL_L,
         RESET_L   => RESET_L,
         clk       => clk,
         DATAIN    => DATAIN,
         MRESP_H   => MRESP_H
      );

END struct;
