-- VHDL Entity ece411.mp3_cpu.symbol
--
-- Created:
--          by - bjohns38.stdt (gllnx19.ews.illinois.edu)
--          at - 01:59:29 10/22/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY mp3_cpu IS
   PORT( 
      CLK     : IN     std_logic;
      RESET_L : IN     std_logic
   );

-- Declarations

END mp3_cpu ;

--
-- VHDL Architecture ece411.mp3_cpu.struct
--
-- Created:
--          by - bjohns38.stdt (gllnx19.ews.illinois.edu)
--          at - 01:59:29 10/22/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;
LIBRARY mp3lib;

ARCHITECTURE struct OF mp3_cpu IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL D_ADDRESSOut : LC3b_word;
   SIGNAL D_DATAOUT    : LC3b_word;
   SIGNAL D_DATAOUt1   : LC3b_word;
   SIGNAL D_MREAD_L    : std_logic;
   SIGNAL F            : STD_LOGIC;
   SIGNAL IDATAAddress : LC3b_word;
   SIGNAL I_DATAOUT    : LC3b_word;
   SIGNAL I_MREAD_L    : std_logic;
   SIGNAL MWRITEL_H    : std_logic;
   SIGNAL MWRITEL_L    : std_logic;


   -- Component Declarations
   COMPONENT PipeLine
   PORT (
      D_DATAIN     : IN     lc3b_word ;
      IDATAIn      : IN     LC3b_word ;
      RESET_L      : IN     std_logic ;
      clk          : IN     std_logic ;
      D_ADDRESSOut : OUT    LC3b_word ;
      D_DATAOUt    : OUT    LC3b_word ;
      D_MREAD_L    : OUT    std_logic ;
      IDATAAddress : OUT    LC3b_word ;
      I_MREAD_L    : OUT    std_logic ;
      MWRITEL_H    : OUT    std_logic ;
      MWRITEL_L    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT DRAM16_DP
   PORT (
      D_ADDRESS  : IN     LC3b_word;
      D_DATAIN   : IN     LC3b_word;
      D_MREAD_L  : IN     std_logic;
      D_MWRITE_L : IN     std_logic;
      I_ADDRESS  : IN     LC3b_word;
      I_MREAD_L  : IN     std_logic;
      RESET_L    : IN     std_logic;
      D_DATAOUT  : OUT    LC3b_word;
      D_MRESP_H  : OUT    std_logic;
      I_DATAOUT  : OUT    LC3b_word;
      I_MRESP_H  : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT OR2
   PORT (
      A : IN     STD_LOGIC ;
      B : IN     STD_LOGIC ;
      F : OUT    STD_LOGIC 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DRAM16_DP USE ENTITY mp3lib.DRAM16_DP;
   FOR ALL : OR2 USE ENTITY mp3lib.OR2;
   FOR ALL : PipeLine USE ENTITY ece411.PipeLine;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : PipeLine
      PORT MAP (
         D_DATAIN     => D_DATAOUT,
         IDATAIn      => I_DATAOUT,
         RESET_L      => RESET_L,
         clk          => CLK,
         D_ADDRESSOut => D_ADDRESSOut,
         D_DATAOUt    => D_DATAOUt1,
         D_MREAD_L    => D_MREAD_L,
         IDATAAddress => IDATAAddress,
         I_MREAD_L    => I_MREAD_L,
         MWRITEL_H    => MWRITEL_H,
         MWRITEL_L    => MWRITEL_L
      );
   U_1 : DRAM16_DP
      PORT MAP (
         D_ADDRESS  => D_ADDRESSOut,
         D_DATAIN   => D_DATAOUt1,
         D_MREAD_L  => D_MREAD_L,
         D_MWRITE_L => F,
         I_ADDRESS  => IDATAAddress,
         I_MREAD_L  => I_MREAD_L,
         RESET_L    => RESET_L,
         D_DATAOUT  => D_DATAOUT,
         D_MRESP_H  => OPEN,
         I_DATAOUT  => I_DATAOUT,
         I_MRESP_H  => OPEN
      );
   U_2 : OR2
      PORT MAP (
         A => MWRITEL_H,
         B => MWRITEL_L,
         F => F
      );

END struct;
