-- VHDL Entity ece411.State_Reg21.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY State_Reg21 IS
   PORT( 
      ADDRESSMUXOut_MEM : OUT    lc3b_word;
      ADDRESSMUXout     : IN     LC3b_word;
      Opcode_EX         : IN     lc3b_opcode;
      opcode_MEM        : OUT    lc3b_opcode;
      destReg_EX        : IN     lc3b_reg;
      destreg_MEM       : OUT    LC3B_REG;
      ALUSHFMuxOut_MEM  : OUT    lc3b_word;
      PCPlus2_EX        : IN     lc3b_word;
      PCPlus2_MEM       : OUT    lc3b_word;
      INSCC_MEM         : OUT    lc3b_nzp;
      INSCC_EX          : IN     lc3b_nzp;
      RESET_L           : IN     std_logic;
      ArithOut          : IN     LC3B_WORD;
      load              : IN     std_logic;
      clk               : IN     std_logic
   );

END State_Reg21 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF State_Reg21 IS 
BEGIN


END generatedInstance;
