-- VHDL Entity ece411.StateReg_31.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY StateReg_31 IS
   PORT( 
      ADDRESSMUXOut_WB  : OUT    LC3b_word;
      D_DATAIN          : IN     lc3b_word;
      opcode_MEM        : IN     lc3b_opcode;
      Opcode_WB         : OUT    LC3b_opcode;
      DEST              : OUT    LC3B_REG;
      destreg_MEM       : IN     LC3B_REG;
      ADDRESSMUXOut_MEM : IN     lc3b_word;
      D_DATAIN_WB       : OUT    LC3b_word;
      PCPlus2_MEM       : IN     lc3b_word;
      PCPLus2_WB        : OUT    LC3b_word;
      ALUSHFMuxOut_MEM  : IN     lc3b_word;
      ALUSHFMUXOut_WB   : OUT    lc3b_word;
      RESET_L           : IN     std_logic;
      load              : IN     std_logic;
      clk               : IN     std_logic
   );

END StateReg_31 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF StateReg_31 IS 
BEGIN


END generatedInstance;
