-- VHDL Entity ece411.State_Reg3.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY State_Reg3 IS
   PORT( 
      PCPlus2_ID   : OUT    lc3b_word;
      index6_ID    : OUT    LC3b_index6;
      offset9_ID   : OUT    LC3b_offset9;
      offset11_ID  : OUT    LC3b_offset11;
      RESET_L      : IN     std_logic;
      IDATAIn      : IN     LC3b_word;
      opcode_ID    : OUT    LC3B_Opcode;
      IR_Bit11     : OUT    std_logic;
      IR_Bit5      : OUT    std_logic;
      imm5_ID      : OUT    LC3b_imm5;
      trapvect8_ID : OUT    lc3b_trapvect8;
      DEST_ID      : OUT    LC3b_reg;
      IR_2_0_ID    : OUT    STD_LOGIC_VECTOR (2 DOWNTO 0);
      IR8_6_ID     : OUT    LC3B_REG;
      IMM4_ID      : OUT    lc3b_imm4;
      INSCC_ID     : OUT    lc3b_nzp;
      IDATAAddress : IN     LC3b_word;
      load         : IN     std_logic;
      clk          : IN     std_logic
   );

END State_Reg3 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF State_Reg3 IS 
BEGIN


END generatedInstance;
