-- VHDL Entity ece411.State_Reg3.generatedInstance
--
-- Created:
--          by - jpatel71.stdt (eelnx34.ews.illinois.edu)
--          at - 12:13:27 10/21/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY State_Reg3 IS
   PORT( 
      ALUout_WB : OUT    LC3b_word;
      DATAIN_WB : OUT    LC3b_word;
      DATAIN    : IN     lc3b_word
   );

END State_Reg3 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF State_Reg3 IS 
BEGIN


END generatedInstance;
