-- VHDL Entity ece411.State_Reg11.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY State_Reg11 IS
   PORT( 
      RFAout_ID  : IN     LC3b_word;
      RFBout_ID  : IN     LC3b_word;
      RFAout_EX  : OUT    LC3b_word;
      ADJ6_ID    : IN     lc3b_word;
      rfbout_ex  : OUT    LC3b_word;
      ADJ9_ID    : IN     LC3b_word;
      PCPlus2_ID : IN     lc3b_word;
      IR5_4_EX   : OUT    lc3b_shfop;
      Imm4_EX    : OUT    lc3b_imm4;
      imm5SEXT   : OUT    LC3b_word;
      ADJ6_EX    : OUT    LC3b_word;
      ADJ11_EX   : OUT    LC3b_word;
      ADJ9_EX    : OUT    LC3b_word;
      PCPlus2_EX : OUT    lc3b_word;
      ADJ8out_EX : OUT    LC3b_word;
      ADJ11_ID   : IN     LC3b_word;
      RESET_L    : IN     std_logic;
      opcode_ID  : IN     LC3B_Opcode;
      Opcode_EX  : OUT    lc3b_opcode;
      ADJ5out    : IN     LC3b_word;
      ADJ8out    : IN     lc3b_word;
      destReg_EX : OUT    lc3b_reg;
      IMM4_ID    : IN     lc3b_imm4;
      INSCC_ID   : IN     lc3b_nzp;
      INSCC_EX   : OUT    lc3b_nzp;
      DEST_ID    : IN     LC3b_reg;
      load       : IN     std_logic;
      clk        : IN     std_logic
   );

END State_Reg11 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF State_Reg11 IS 
BEGIN


END generatedInstance;
