-- VHDL Entity ece411.way512b.symbol
--
-- Created:
--          by - tmurray5.stdt (eelnx39.ews.illinois.edu)
--          at - 16:45:04 11/16/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY way512b IS
   PORT( 
      dataIn    : IN     lc3b_oword;
      dataWrite : IN     std_logic;
      dirtyIn   : IN     std_logic;
      index     : IN     lc3b_index5;
      reset_l   : IN     std_logic;
      tagIn     : IN     lc3b_l2tag;
      dataOut   : OUT    lc3b_oword;
      dirtyOut  : OUT    std_logic;
      tagOut    : OUT    lc3b_l2tag;
      validOut  : OUT    std_logic
   );

-- Declarations

END way512b ;

--
-- VHDL Architecture ece411.way512b.struct
--
-- Created:
--          by - tmurray5.stdt (eelnx39.ews.illinois.edu)
--          at - 16:45:05 11/16/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF way512b IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT dataArray512B
   PORT (
      dataIn    : IN     lc3b_oword ;
      dataWrite : IN     std_logic ;
      index     : IN     lc3b_index5 ;
      reset_l   : IN     std_logic ;
      dataOut   : OUT    lc3b_oword 
   );
   END COMPONENT;
   COMPONENT dirtyArray512B
   PORT (
      dataWrite : IN     std_logic ;
      dirtyIn   : IN     std_logic ;
      index     : IN     lc3b_index5 ;
      reset_l   : IN     std_logic ;
      dirtyOut  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT tagArray512B
   PORT (
      dataWrite : IN     std_logic ;
      index     : IN     lc3b_index5 ;
      reset_l   : IN     std_logic ;
      tagIn     : IN     lc3b_l2tag ;
      tagOut    : OUT    lc3b_l2tag 
   );
   END COMPONENT;
   COMPONENT validArray512B
   PORT (
      dataWrite : IN     std_logic ;
      index     : IN     lc3b_index5 ;
      reset_l   : IN     std_logic ;
      validOut  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : dataArray512B USE ENTITY ece411.dataArray512B;
   FOR ALL : dirtyArray512B USE ENTITY ece411.dirtyArray512B;
   FOR ALL : tagArray512B USE ENTITY ece411.tagArray512B;
   FOR ALL : validArray512B USE ENTITY ece411.validArray512B;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aDataArray512B : dataArray512B
      PORT MAP (
         dataIn    => dataIn,
         dataWrite => dataWrite,
         index     => index,
         reset_l   => reset_l,
         dataOut   => dataOut
      );
   aDirtyArray512B : dirtyArray512B
      PORT MAP (
         dataWrite => dataWrite,
         dirtyIn   => dirtyIn,
         index     => index,
         reset_l   => reset_l,
         dirtyOut  => dirtyOut
      );
   aTagArray512B : tagArray512B
      PORT MAP (
         dataWrite => dataWrite,
         index     => index,
         reset_l   => reset_l,
         tagIn     => tagIn,
         tagOut    => tagOut
      );
   aValidArray512B : validArray512B
      PORT MAP (
         dataWrite => dataWrite,
         index     => index,
         reset_l   => reset_l,
         validOut  => validOut
      );

END struct;
