-- VHDL Entity ece411.writer.symbol
--
-- Created:
--          by - tmurray5.stdt (eelnx37.ews.illinois.edu)
--          at - 15:42:48 10/14/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY writer IS
   PORT( 
      DataOut     : IN     lc3b_word;
      decodeOut   : IN     std_logic;
      lineData    : IN     lc3b_word;
      mwriteh_l   : IN     std_logic;
      mwritel_l   : IN     std_logic;
      lineDataOut : OUT    lc3b_word
   );

-- Declarations

END writer ;

--
-- VHDL Architecture ece411.writer.struct
--
-- Created:
--          by - tmurray5.stdt (eelnx37.ews.illinois.edu)
--          at - 15:42:48 10/14/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF writer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL f         : std_logic;
   SIGNAL f1        : std_logic;
   SIGNAL high      : lc3b_byte;
   SIGNAL highByte  : lc3b_byte;
   SIGNAL highByte1 : lc3b_byte;
   SIGNAL low       : lc3b_byte;
   SIGNAL lowByte   : LC3b_byte;
   SIGNAL lowByte1  : LC3b_byte;
   SIGNAL sel       : std_logic;
   SIGNAL sel1      : std_logic;


   -- Component Declarations
   COMPONENT byteCombiner
   PORT (
      high        : IN     lc3b_byte ;
      low         : IN     lc3b_byte ;
      lineDataOut : OUT    lc3b_word 
   );
   END COMPONENT;
   COMPONENT byteMux2
   PORT (
      sel : IN     std_logic ;
      a   : IN     lc3b_byte ;
      b   : IN     lc3b_byte ;
      f   : OUT    lc3b_byte 
   );
   END COMPONENT;
   COMPONENT highLow
   PORT (
      datain   : IN     lc3b_word ;
      highByte : OUT    lc3b_byte ;
      lowByte  : OUT    LC3b_byte 
   );
   END COMPONENT;
   COMPONENT notGate
   PORT (
      A : IN     std_logic ;
      f : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT writeSel
   PORT (
      decodeOut : IN     std_logic ;
      mwrite    : IN     std_logic ;
      sel       : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : byteCombiner USE ENTITY ece411.byteCombiner;
   FOR ALL : byteMux2 USE ENTITY ece411.byteMux2;
   FOR ALL : highLow USE ENTITY ece411.highLow;
   FOR ALL : notGate USE ENTITY ece411.notGate;
   FOR ALL : writeSel USE ENTITY ece411.writeSel;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aByteComb : byteCombiner
      PORT MAP (
         high        => high,
         low         => low,
         lineDataOut => lineDataOut
      );
   byteMux2_0 : byteMux2
      PORT MAP (
         sel => sel,
         a   => highByte,
         b   => highByte1,
         f   => high
      );
   byteMux2_1 : byteMux2
      PORT MAP (
         sel => sel1,
         a   => lowByte,
         b   => lowByte1,
         f   => low
      );
   ahighLow0 : highLow
      PORT MAP (
         datain   => lineData,
         highByte => highByte,
         lowByte  => lowByte
      );
   ahighLow1 : highLow
      PORT MAP (
         datain   => DataOut,
         highByte => highByte1,
         lowByte  => lowByte1
      );
   U_0 : notGate
      PORT MAP (
         A => mwritel_l,
         f => f
      );
   U_1 : notGate
      PORT MAP (
         A => mwriteh_l,
         f => f1
      );
   aWriteSel : writeSel
      PORT MAP (
         decodeOut => decodeOut,
         mwrite    => f,
         sel       => sel1
      );
   aWriteSel1 : writeSel
      PORT MAP (
         decodeOut => decodeOut,
         mwrite    => f1,
         sel       => sel
      );

END struct;
