-- VHDL Entity ece411.WriteLogic1.generatedInstance
--
-- Created:
--          by - tmurray5.stdt (eelnx23.ews.illinois.edu)
--          at - 16:25:58 11/04/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.NUMERIC_STD.all;
USE ieee.std_logic_1164.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WriteLogic1 IS
   PORT( 
      D_MWRITEH_L  : OUT    std_logic;
      D_MWRITEL_L  : OUT    std_logic;
      D_ADDRESSOut : IN     LC3b_word;
      opcode_MEM   : IN     lc3b_opcode;
      clk          : IN     std_logic
   );

END WriteLogic1 ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF WriteLogic1 IS 
BEGIN


END generatedInstance;
